/**
 * js/utils/helpers.js
 *
 * This file contains miscellaneous helper and utility functions that are used
 * across the application. Separating these into their own file keeps the
 * main component logic clean and promotes code reuse.
 */

/**
 * Handles sharing content using the Web Share API with a fallback to clipboard.
 * @param {object} shareData - The data to be shared (title, text, url).
 * @param {function} onCopySuccess - A callback function to trigger on successful copy.
 */
export const handleShare = async (shareData, onCopySuccess) => {
    trackEvent('share', 'General'); // Assuming a general context for sharing
    if (navigator.share) {
        try {
            await navigator.share(shareData);
        } catch (err) {
            console.error("Share failed:", err);
        }
    } else {
        // Fallback for browsers that don't support Web Share API
        navigator.clipboard.writeText(shareData.text || shareData.url);
        onCopySuccess(); // Trigger a toast or notification in the main app
    }
};

/**
 * Handles copying rich text (HTML) with a plain text fallback to the clipboard.
 * It also appends an attribution to the copied content.
 * @param {string} markdownContent - The markdown content to be copied.
 * @param {function} onCopySuccess - A callback function to trigger on successful copy.
 * @param {function} onError - A callback to handle potential errors.
 */
export const handleCopyToClipboard = async (markdownContent, onCopySuccess, onError) => {
    try {
        const htmlContent = marked.parse(markdownContent);
        const container = document.createElement('div');
        container.innerHTML = htmlContent;
        
        // Create and append the attribution
        const attribution = document.createElement('p');
        attribution.innerHTML = '<br><br>---<br><em>Generated by the CBC AI Educational Assistant</em><br><em>Created by Derrick Musamali | Visit: <a href="https://cbc-ai-tool.netlify.app/">https://cbc-ai-tool.netlify.app/</a></em>';
        container.appendChild(attribution);
        
        const finalHtml = container.innerHTML;
        const plainText = container.innerText;

        // Create Blob objects for the Clipboard API
        const blobHtml = new Blob([finalHtml], { type: 'text/html' });
        const blobText = new Blob([plainText], { type: 'text/plain' });
        
        await navigator.clipboard.write([
            new ClipboardItem({
                'text/html': blobHtml,
                'text/plain': blobText
            })
        ]);
        onCopySuccess(); // Notify the user of success
    } catch (err) {
        console.error('Rich text copy failed, falling back to plain text. Error:', err);
        try {
            // Fallback to plain text for browsers that don't support rich text copy
            const plainText = marked.parse(markdownContent).replace(/<[^>]*>/g, '');
            const attributionText = "\n\n---\nGenerated by the CBC AI Educational Assistant\nCreated by Derrick Musamali | Visit: https://cbc-ai-tool.netlify.app/";
            await navigator.clipboard.writeText(plainText + attributionText);
            onCopySuccess(); // Notify the user of success
        } catch (fallbackErr) {
            console.error('Plain text fallback copy failed:', fallbackErr);
            onError("Failed to copy message. Your browser might not support this feature.");
        }
    }
};